- name: "install nodejs and npm"
  become: true
  apt:
    name: ["nodejs", npm]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm: 
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Executing pm2"
  shell:
    pm2 stop default

- name: "Starting App"
  shell:
    pm2 start npm -- start