
- name: Creates directory
  file:
    path: ~/backend_app
    state: directory

- name: Extract the zipped artifact
  unarchive: 
    src: ~/artifact.tar.gz
    dest: ~/backend_app

- name: Install dependencies
  args:
    chdir: ~/project/backend_app
  command: |
    npm install
    pm2 stop default
    pm2 start npm -- start