
- name: Extract the zipped artifact
  unarchive: 
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: Install dependencies
  shell: |
    # npm install
    # pm2 stop default
    pm2 start npm -- start