
- name: "Move backend files to web server"
  become: true
  unarchive:
    src: ~/project/.circleci/ansible/roles/deploy/files/artifact.tar.gz
    dest: .

- name: "install nodejs and npm"
  become: true
  apt:
    name: ["nodejs", npm]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm: 
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Executing Node"
  shell: |
    pm2 stop all

- name: "Starting App"
  shell: |
    pm2 start npm -- start