
- name: "install nodejs and npm"
  become: true
  apt:
    name: ["nodejs", npm]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm: 
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Move backend files to web server"
  # become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "Starting App"
  shell: |
    sudo pm2 stop default
    sudo pm2 start npm -- start
